import React,{useEffect,useState} from 'react';
import {cloudRequest} from './cloud-client.js';
import {presenceLabel,validateBusiness} from './business.js';
import './business-admin.css';
export default function BusinessAdmin({onOpenProject}) {
  const [businesses,setBusinesses]=useState([]),[editing,setEditing]=useState(null),[overview,setOverview]=useState(null),[projectRows,setProjectRows]=useState([]),[hasMore,setHasMore]=useState(false),[filter,setFilter]=useState(''),[month,setMonth]=useState(new Date(Date.now()+330*60000).toISOString().slice(0,7)),[error,setError]=useState(''),[busy,setBusy]=useState(false),[review,setReview]=useState(null);
  async function run(fn){setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function refresh(){const [b,o,p]=await Promise.all([cloudRequest('businesses'),cloudRequest('overview',{params:{month}}),cloudRequest('projects',{params:filter?{businessId:filter}:{}})]);setBusinesses(b.businesses);setOverview(o);setProjectRows(p.projects);setHasMore(p.hasMore);}
  useEffect(()=>{let stopped=false,inFlight=false;const update=async(initial=false)=>{if(stopped||inFlight||document.visibilityState==='hidden')return;inFlight=true;try{const [b,o,p]=await Promise.all([cloudRequest('businesses'),cloudRequest('overview',{params:{month}}),initial?cloudRequest('projects',{params:filter?{businessId:filter}:{}}):null]);if(!stopped){setBusinesses(b.businesses);setOverview(o);if(p){setProjectRows(p.projects);setHasMore(p.hasMore);}setError('');}}catch(e){if(!stopped)setError(e.message);}finally{inFlight=false;}};update(true);const timer=setInterval(()=>update(),30000);return()=>{stopped=true;clearInterval(timer);};},[month,filter]);
  const edit=(key,value)=>setEditing(old=>({...old,[key]:value}));
  const businessName=id=>businesses.find(b=>b.id===id)?.name||id;
  const visibleStaff=overview?.staff.filter(s=>!filter||s.businessId===filter)||[],visibleStats=overview?.stats.filter(s=>!filter||s.businessId===filter)||[];
  const widget=key=>visibleStats.reduce((sum,row)=>sum+(Number(row[key])||0),0);
  async function logo(file){
    if(!['image/png','image/jpeg'].includes(file.type)||file.size>3e6)throw Error('Use a JPG/PNG logo smaller than 3 MB.');
    const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const scale=Math.min(1,400/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);edit('brand',{...editing.brand,logo:c.toDataURL('image/jpeg',.9)});}finally{URL.revokeObjectURL(url);}
  }
  return <section className="business-admin"><h2>Owner control centre</h2><p>Both businesses. Your staff see only their own projects. Activity is an approximate app signal, not proof of continuous work.</p>
    {error&&<p className="workspace-alert" role="alert">{error}</p>}
    <div className="admin-widgets"><article><span>Businesses</span><strong>{filter?1:businesses.length}</strong></article><article><span>Operators</span><strong>{visibleStaff.length}</strong></article><article><span>Active now</span><strong>{visibleStaff.filter(s=>presenceLabel(s)==='Active recently').length}</strong></article><article><span>Projects</span><strong>{widget('total')}</strong></article><article><span>Approved this month</span><strong>{widget('approved')}</strong></article><article><span>Allocated bar tokens</span><strong>{visibleStaff.reduce((n,s)=>n+(s.barTokens||0),0)}</strong></article></div>
    <div className="row">{businesses.map(b=><button className="secondary" key={b.id} onClick={()=>setEditing(structuredClone(b))}>{b.name} · settings</button>)}</div>
    {editing&&<form className="business-settings" onSubmit={e=>{e.preventDefault();run(async()=>{validateBusiness(editing);const {business}=await cloudRequest('businesses',{method:'PATCH',body:editing});setEditing(business);await refresh();});}}>
      <h3>{editing.name} · branding, quotations & pricing</h3><p>Changes apply to newly created projects. Existing projects retain their saved business settings and rates.</p>
      <label className="field">Business name<input required maxLength={70} value={editing.name} onChange={e=>edit('name',e.target.value)}/></label>
      <div className="business-fields">{['address','phone','email','payee','bank','account','watermark'].map(k=><label className="field" key={k}>{k}<input maxLength={k==='address'?300:100} value={editing.brand[k]} onChange={e=>edit('brand',{...editing.brand,[k]:e.target.value})}/></label>)}</div>
      {editing.brand.logo&&<img className="business-logo" alt="Business logo" src={editing.brand.logo}/>}
      <label className="field">Upload business logo<input type="file" accept="image/png,image/jpeg" onChange={e=>{const f=e.target.files[0];e.target.value='';if(f)run(()=>logo(f));}}/></label>
      <div className="business-fields">{['base','upper','tall'].map(k=><label className="field" key={k}>{k} calculation<select value={editing.formula[k]} onChange={e=>edit('formula',{...editing.formula,[k]:e.target.value})}>{(k==='tall'?[['height_ft','Sum of tall heights · ft'],['width_ft','Sum of tall widths · ft']]:[['linear_ft','Run length · ft'],['front_sqft','External cabinet front area · sq ft']]).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>)}</div>
      <p>Rates use the selected calculation units. Granite: sq ft; splash/LED: linear ft; services: per job. Area means external cabinet width × height, not individual door material.</p>
      <div className="business-fields">{Object.keys(editing.salesRates).map(k=><label className="field" key={k}>{k} rate · LKR<input type="number" required min="0" max="1000000000" value={editing.salesRates[k]} onChange={e=>edit('salesRates',{...editing.salesRates,[k]:e.target.value===''?'':Number(e.target.value)})}/></label>)}</div>
      <label className="field">Default advance %<input type="number" required min="0" max="100" value={editing.advancePercent} onChange={e=>edit('advancePercent',Number(e.target.value))}/></label>
      <label className="field">Default quotation conditions<textarea rows="8" maxLength={14000} value={editing.terms} onChange={e=>edit('terms',e.target.value)}/></label>
      <button className="primary" disabled={busy}>Save business settings</button> <button type="button" className="secondary" disabled={busy} onClick={()=>setEditing(null)}>Close settings</button>
    </form>}
    <h3>Targets & recent use</h3><div className="row"><label className="field">Reporting month · Sri Lanka<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><label className="field">Business<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Both businesses</option>{businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><button className="secondary" disabled={busy} onClick={()=>run(refresh)}>Refresh</button></div>
    <p>Counts exclude Trash. Target = standing monthly target for currently approved, unchanged projects reviewed in this month. Newly saved edits require review again. Updates approximately every 30 seconds.</p>
    <div className="business-table"><table><thead><tr><th>Staff / business</th><th>App signal</th><th>Projects</th><th>Created</th><th>Approved / target</th><th>Bar tokens</th></tr></thead><tbody>{visibleStaff.map(s=>{const counts=overview.stats.filter(x=>x.ownerId===s.id&&x.businessId===s.businessId),total=k=>counts.reduce((n,r)=>n+r[k],0);return <tr key={s.id}><td>{s.username||s.name||s.id}<small>{businessName(s.businessId)} · {s.status}</small></td><td>{presenceLabel(s)}<small>{s.lastSeen?new Date(s.lastSeen).toLocaleString():'No activity signal yet'}</small>{s.projectId&&<button className="text" onClick={()=>run(async()=>{const {project}=await cloudRequest('project',{params:{id:s.projectId}});onOpenProject?.(project);})}>Open last reported project</button>}</td><td>{total('total')}</td><td>{total('created')}</td><td>{total('approved')} / {s.monthlyTarget||'not set'}</td><td>{s.barTokens||0}<small>1 token = 1 bar</small></td></tr>;})}</tbody></table></div>
    <div className="project-grid">{businesses.filter(b=>!filter||b.id===filter).map(b=>{const counts=overview?.stats.filter(s=>s.businessId===b.id)||[],sum=k=>counts.reduce((n,s)=>n+s[k],0);return <article className="project-card" key={b.id}><h3>{b.name}</h3><p>{sum('total')} projects · {sum('created')} created this month · {sum('approved')} approved this month</p><small>Includes projects retained in this business after staff reassignment.</small></article>;})}</div>
    <h3>Saved project quality review</h3><p>Open the actual design before approval. Approval is your judgement, not an automatic quality score. Use Refresh for the latest project list; only activity totals refresh automatically.</p>
    <div className="cloud-list">{projectRows.map(p=><div className="business-project" key={p.id}><strong>{p.name}</strong><small>{businessName(p.businessId)} · {p.owner} · saved revision {p.revision} · {p.reviewedRevision===p.revision?p.reviewStatus:'needs review'}</small><div className="row"><button className="primary" onClick={()=>run(async()=>{const {project}=await cloudRequest('project',{params:{id:p.id}});onOpenProject?.(project);})}>Open design</button><button className="secondary" onClick={()=>setReview({id:p.id,name:p.name,revision:p.revision,status:p.reviewedRevision===p.revision?p.reviewStatus:'draft',note:p.reviewNote||''})}>Record review</button></div></div>)}</div>
    {hasMore&&<button className="secondary" disabled={busy} onClick={()=>run(async()=>{const r=await cloudRequest('projects',{params:{offset:String(projectRows.length),...(filter?{businessId:filter}:{})}});setProjectRows(old=>[...old,...r.projects]);setHasMore(r.hasMore);})}>Load more projects</button>}
    {review&&<form onSubmit={e=>{e.preventDefault();run(async()=>{await cloudRequest('review',{method:'PATCH',body:review});setReview(null);await refresh();});}}><h3>Review: {review.name} · revision {review.revision}</h3><label className="field">Decision<select value={review.status} onChange={e=>setReview({...review,status:e.target.value})}><option value="draft">Not reviewed</option><option value="changes_requested">Changes requested</option><option value="approved">Approved</option></select></label><label className="field">Feedback / corrections<textarea maxLength={6000} rows="4" value={review.note} onChange={e=>setReview({...review,note:e.target.value})}/></label><button className="primary" disabled={busy}>Save review</button> <button type="button" className="secondary" onClick={()=>setReview(null)}>Cancel</button></form>}
  </section>;
}
